### ISSUE TITLE
pleaseconvince.meJsonsE

### ISSUE THREAD

**Issue by jrabbass** [jhannah/pleaseconvince.me#2]
I think I may have this figured out. I would like to introduce some color to the site and maybe some graphics. See what you think of this.

**Comment by jhannah** [comment]
Hi Jason. I see that you forked my repo, but it looks like you haven't pushed any changes to your repo? Once you do there will be a "Create Pull Request" button on github, which will open a PR showing me your proposed changes. Thanks. :)

**Comment by jrabbass** [comment]
Ok. Still figuring this Github stuff out. I'll have something soon.
